---
- hosts: quickies_nodes
  become: yes
  vars:
    quickies_url: https://github.com/nst/Quickies.git
    db_name: quickies 
    db_user: quickies_public
    db_password: ''
    db_host: localhost
  tasks:
    - name: "Install http server"
      yum:
        name: httpd
        state: latest	
    - name: "instal php module"
      yum:
        name: "{{item}}"
        state: latest
      with_items:
        - php
        - php-mysql
        - php-curl
        - php-gd
        - php-xml
        - php-dom
        - php-mbstring
	- name: "configure vhost"
      template:
        src: templates/vhosts.conf
        dest: /etc/httpd/conf.d/cloud.conf	
    - name: "download quickies"
      get_url:
        url: "{{quickies_url}}"
        dest: ~/quickies.zip
    - name: "Unpack archive"
      unarchive:
        src: ~/quickies.zip
        dest: /var/www/
        remote_src: yes
	- name: "set apache as application owner"
      file:
        dest: /var/www/quickies/
        owner: apache
        group: apache
    - name: "Install mariadb"
      yum:
        name: ["mariadb", "mariadb-server", "MySQL-python"]
        state: latest
    - name: "Restart mariadb"  
      service:
        name: mariadb
        state: restarted
    - name: "set up quickies db"
      mysql_db:
        name: "{{db_name}}"`
        state: present
	- name: "set up db user"	
	  mysql_user:
		name: "{{db_user}}"
		password: "{{db_password}}"
		priv: '*.*:ALL'
		state: present	
    - name: "start httpd server"
      service:
        name: httpd
        state: restarted	
    - name: "solve problem: Can't create data directory"
      file:
        dest: /var/www/quickies/
        owner: apache
        group: apache